CREATE TABLE if not exists USERS(
   ID INT AUTO_INCREMENT PRIMARY KEY,
   FIRSTNAME VARCHAR(255),
   LASTNAME VARCHAR(255),
   EMAIL VARCHAR(255),
   PASSWORD VARCHAR(255)
);

CREATE TABLE if not exists TOKENS(
   ID INT AUTO_INCREMENT PRIMARY KEY,
   TOKEN VARCHAR(255),
   CREATEDDATE DATE,
   USERID INT
);