CREATE TABLE if not exists USERS(
   ID INT,
   FIRSTNAME VARCHAR(255),
   LASTNAME VARCHAR(255),
   EMAIL VARCHAR(255),
   PASSWORD VARCHAR(255)
);
   
CREATE TABLE if not exists ITEMS(
   ID INT,
   name VARCHAR(255)
)
